### ISSUE TITLE
QA checklist

### ISSUE THREAD

**Issue by andrejus-notcat** [gluon-project/gluon-specs#21]
QA checklist

New token (create new token)
- [ ] new token
- [ ] create new
- [ ] enter token name
- [ ] enter token symbol
- [ ] exponent 2
- [ ] push ‘‘create token‘‘ button 
- [ ] new token appeared in wallet token list

New token (add token from the list)
- [ ] new token
- [ ] add existing
- [ ] click on token from the list
- [ ] token appeared in wallet token list

New token (add existing tokens)
- [ ] new token
- [ ] add existing
- [ ] add adress (token contract address)
- [ ] name of token appears in ‘‘name‘‘ field; symbol of token appears in ‘‘symbol‘‘ screen
- [ ] push ‘‘add button‘‘
- [ ] token appeared in wallet token list

Buy GLU token 
- [ ] select GLU token
- [ ] ‘‘buy‘‘ field is highlighted 
- [ ] enter desired amount in ‘‘amount‘‘ screen
- [ ] Price/cost in ETH changes according to amount of GLU tokens 
- [ ] Bonding curve moves to the right size according to the amount of GLU tokens 
- [ ] click ‘‘buy‘‘ button 
- [ ] amount of GLU tokens increased 
- [ ] amount of ETH tokens decreased

Sell GLU tokens
- [ ] select GLU token
- [ ] ‘‘buy‘‘ field is highlighted
- [ ] push on ‘‘sell‘‘ field not highlighted
- [ ] ‘‘sell‘‘ field is highlighted 
- [ ] enter desired to sell amount in ‘‘amount screen‘‘ 
- [ ] reward in ETH changes according to amount of GLU tokens
- [ ] Bonding curve moves to the left size according to the amount of GLU tokens 
- [ ] click ‘‘sell‘‘ button 
- [ ] amount of GLU tokens decreased 
- [ ] amount of ETH tokens increased

Buy any other token
- [ ] select token
- [ ] ‘‘buy‘‘ field is highlighted 
- [ ] enter desired to buy amount in ‘‘amount‘‘ screen
- [ ] Price in GLU of selected token appears and changes according to amount
- [ ] Bonding curve moves to the right size according to the amount of selected tokens 
- [ ] click ‘‘buy‘‘ button 
- [ ] amount of selected tokens increased 
- [ ] amount of GLU tokens decreased

Sell any other token
- [ ] select token
- [ ] ‘‘buy‘‘ field is highlighted
- [ ] push on ‘‘sell‘‘ field not highlighted
- [ ] ‘‘sell‘‘ field is highlighted 
- [ ] enter desired to sell amount in ‘‘amount screen‘‘ 
- [ ] reward in GLU of selected tokens appears and changes according to amount 
- [ ] Bonding curve moves to the left size according to the amount of selected tokens 
- [ ] click ‘‘sell‘‘ button 
- [ ] amount of selected tokens decreases 
- [ ] amount of GLU tokens increases

Send token to receiver from list
- [ ] Click on ‘‘send‘‘ button in tab bar
- [ ] ‘‘send‘‘ button gets highlighted
- [ ] sender is selected automatically 
- [ ] select token from list 
- [ ] selected token appears in ‘‘request‘‘ tab bar ‘‘select token‘‘ field
- [ ] set amount 
- [ ] selected amount appears in request tab
- [ ] Select receiver
- [ ] list of receivers appears
- [ ] click on receiver 
- [ ] seleceted receiver appears Send tab bar
- [ ] attach something - enter message and URL or enter message and choose photo
- [ ] when preferred data is attached push ‘‘set attachment‘‘ button 
- [ ] message text appears in ‘‘attach something‘‘ field
- [ ] push ‘‘Send‘‘ button
- [ ] transaction completed 
- [ ] automatically moved to feed screen 
- [ ] transaction with sender, receiver, amount of sent tokens, time/date and attachment appears in the feed screen.

Send token to new receiver 
- [ ] Click on ‘‘send‘‘ button in tab bar 
- [ ] ‘‘send‘‘ button gets highlighted
- [ ] sender is selected automatically 
- [ ] select token from list 
- [ ] selected token appears in request tab bar ‘‘select token‘‘ field
- [ ] set amount 
- [ ] selected amount appears in request tab
- [ ] Select receiver
- [ ] list of receivers appears
- [ ] click on ‘‘Add‘‘ button
- [ ] Add Receiver screen appears
- [ ] Fill in ‘‘Name‘‘ field, fill in ‘‘Address‘‘ field (receiver has to be real contract number)
- [ ] Push ‘‘Save‘‘ button 
- [ ] Newly created receiver appears in Send tab bar
- [ ] attach something - enter message and URL or enter message and choose photo
- [ ] when preferred data is attached push ‘‘set attachment‘‘ button 
- [ ] message text appears in ‘‘attach something‘‘ field
- [ ] push ‘‘Send‘‘ button
- [ ] transaction completed 
- [ ] automatically moved to feed screen
- [ ] transaction with sender, receiver, amount of sent tokens, time/date and attachment appears in the feed screen.

Request token
- [ ] Click on ‘‘request‘‘ button 
- [ ] ‘‘request‘‘ button gets highlighted
- [ ] receiver is selected automatically 
- [ ] select token from list 
- [ ]  selected token appears in request tab bar ‘‘select token‘‘ field
- [ ] set amount 
- [ ] selected amount appears in request tab
- [ ] attach something - enter message and URL or enter message and choose photo
- [ ] message text appears in ‘‘attach something‘‘ field
- [ ] push ‘‘request‘‘ button
- [ ] request screen pops up with URL
- [ ] push ‘‘copy‘‘ button – nothing happens
- [ ] push ‘‘close‘‘ button
- [ ] paste/send copied link
- [ ] copied link looks like Gluon web page preview
 

Tokens receiver
- [ ] sender has to inform receiver (messenger, mail, etc.) that tokens are sent and has to tell the name of the token or token contract address
- [ ] receiver has to go to wallet 
- [ ] new token
- [ ]  add existing
- [ ] click on token from the list or add token contract address
- [ ]  token appears in the wallet with sent amount 
- [ ] transaction with attachment appears in feed

Interaction with token request link
- [ ] internet user sees the link and clicks on it
- [ ] link forwards to gluon.space
- [ ] ‘‘send‘‘ tab bar button highlighted
- [ ] sender is autofilled
- [ ] ‘‘Select token“ is filled with token name
- [ ] “Set amount“ is filled with requested amount and symbol of token
- [ ] “receiver“ is filled with address 
- [ ] “Attach something“ 
- [ ] Push “Set attachment“ button
- [ ] Push “Send button“
